### PR TITLE
Use SECRET_KEY code from rpahendyr-django-essentials

### PR DESCRIPTION
**Pull request by raphendyr**
# Description

Copied Django easy-of-life changes from A+/MOOC-Grader to Radar. I haven't tested these, but I think they should work (thus the PR).

This also includes environment variables to make container based development easier.

# Testing

Check that the Django stil lstarts ok and the `local_settings.py` is found correctly.

# Is it [Done](https://wiki.aalto.fi/display/EDIT/Definition+of+Done)?

*Clean up your git commit history before submitting the pull request!*

- [ ] I (developer) have created unit tests and the tests pass
- [ ] I (developer) have created functional tests (Selenium tests) if applicable
- [ ] I (developer) have tested the changes manually
- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

### CODE REVIEW

**Review by Mankro — COMMENTED** [review]
Some day, I am supposed to test that this works (probably does). The new installation guide shows how to create the secret key manually in the old way so that will need to be updated too when this PR is merged.

**Comment by raphendyr** [comment]
FYI: I started to make container usage a bit easier with [this commit](https://github.com/raphendyr/raphendyr-django-essentials/commit/980cffe73d5838b13cc453fe0a977dc682cd3aaa), but I didn't have time to finalize it.

The goal was to make settings look like

```python
update_settings_with_file(__name__, 'local_settings', from_environ='RADAR_LOCAL_SETTINGS')
update_secret_from_file(__name__, 'secret_key', from_environ='RADAR_SECRET_KEY_FILE')
```
It's still missing the `quiet` part.

**Comment by Gehock** [comment]
I tested the changes, rebased on top of the current head and slightly updated the documentation here: https://github.com/gehock/radar/tree/auto-secret-key

I don't have the permission to force-push into this current PR, do you want to do that yourself or should I open a new PR?

**Comment by Mankro** [comment]
@Gehock I can merge the code now. No need for a new PR. Thanks!

**Pull request merged**
